services:
  - type: web
    name: yunusobod-bozori
    runtime: docker
    plan: free
    region: frankfurt
    healthCheckPath: /api/health
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: PORTER_PIN
        sync: false
      - key: APP_ENV
        value: production
